Adding tests for bzr plugin
gobuffalo/buffalo-cli pull request #23
Opened 2020-01-10 12:28 UTC by paganotoni

Adding some tests for BZR as this plugin depends on the Bzr command output I had to mock the response of the command. Looking forward to your input on the approach I took. In case it's good I could use the same for the git plugin.

2020-01-11 21:35 UTC, markbates requested changes

2020-01-11 21:35 UTC, markbates commented on cli/internal/plugins/bzr/bzr.go
> +	name        = "bzr"
Try to avoid package level state and context. What if a second bzr plugin is added?

2020-01-11 21:35 UTC, markbates commented on cli/internal/plugins/bzr/bzr.go
> +var testConfig = struct {
again, no package state, and there should be any mention of testing outside of the tests themselves.

2020-01-11 21:35 UTC, markbates commented on cli/internal/plugins/bzr/bzr.go
> +type Buffalo struct{}
Let's rename this to something more descriptive, like `Version` or `Versioner`.

2020-01-11 21:35 UTC, markbates commented on cli/internal/plugins/bzr/bzr.go
> +	if testConfig.enabled {
Try using an interface here, like the one from `buffalo build`

```go
type Runner interface {
	plugins.Plugin
	RunBuild(ctx context.Context, cmd *exec.Cmd) error
}
```

https://github.com/gobuffalo/buffalo-cli/blob/resource/cli/internal/plugins/buildcmd/ifaces.go#L64
https://github.com/gobuffalo/buffalo-cli/blob/resource/cli/internal/plugins/buildcmd/ifaces_test.go#L213
https://github.com/gobuffalo/buffalo-cli/blob/resource/cli/internal/plugins/buildcmd/main_test.go#L14

2020-01-13 02:26 UTC, paganotoni commented
Wow! Thanks for the feedback @markbates, I really appreciate it. I updated the code to use an interface when interacting with the CLI. I feel I could use your input on the naming.

As for the interface, I'm not sure if it should live here or in another place, I imagine that the `git` `versioner` will be very similar to this one.

2020-01-13 12:23 UTC, markbates commented on cli/internal/plugins/bzr/version_runner.go
> +	ToolAvailable() (bool, error)
Remove this function from the interface. It’s not necessary.

2020-01-13 12:24 UTC, markbates commented on cli/internal/plugins/bzr/bzr_versioner.go
> +	versionRunner VersionRunner
Look at how build, test, generate, etc... are doing this. They search through the plugins to find an implementation.

2020-01-13 12:25 UTC, markbates commented on cli/internal/plugins/bzr/version_runner.go
> +	RunVersionCommand(context.Context, *bytes.Buffer) error
Look at the way the other plugins define similar patterns. Please use those.

2020-01-13 12:25 UTC, markbates commented on cli/internal/plugins/bzr/bzr_version_runner.go
> +type BzrVersionRunner struct{}
This type is unnecessary.

2020-01-16 16:39 UTC, markbates requested changes

2020-01-16 16:39 UTC, markbates commented on cli/internal/plugins/bzr/versioner.go
> +		if _, err := exec.LookPath("bzr"); err != nil {
Remove the check, as its unneeded. when you try to run the command it'll return an error if it can't find it.

2020-01-16 16:39 UTC, markbates commented on cli/internal/plugins/bzr/bzr_test.go
> +type testVersionRunner struct {
you don't need this type. you have `versionRunner` in `ifaces_test.go`. you can use that. :)

2020-01-16 23:54 UTC, paganotoni commented
@markbates ready when you are :)

2020-01-20 13:04 UTC, paganotoni commented
@markbates this one is ready to be reviewed. Please LMK if it's ready to be merged.

2020-01-20 14:35 UTC, markbates approved these changes

2020-01-22 18:29 UTC, merged